version: '3.8'

services:
  trading_bot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crypto_trading_bot
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      - ./config:/app/config
    environment:
      - TZ=UTC
      # Set trading bot configuration (edit according to your needs)
      - TRADING_BOT_MODE=paper  # paper, live
      - TRADING_BOT_STRATEGIES=rsi,macd,bollinger  # Comma-separated strategies to use
      - TRADING_BOT_LOG_LEVEL=INFO  # DEBUG, INFO, WARNING, ERROR
      # If using live mode, uncomment and add your API keys
      # - BINANCE_API_KEY=your_api_key_here
      # - BINANCE_API_SECRET=your_api_secret_here
    ports:
      - "8502:8502"  # Streamlit app
      - "5000:5000"  # MLflow server
    command: ["--debug"]  # Remove this for production use
    networks:
      - trading_network

  # Optional PostgreSQL database for storing trading data
  # Uncomment if you want to use PostgreSQL instead of SQLite
  # postgres:
  #   image: postgres:14-alpine
  #   container_name: trading_db
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=crypto
  #     - POSTGRES_PASSWORD=crypto_password
  #     - POSTGRES_DB=trading_bot
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - trading_network

networks:
  trading_network:
    driver: bridge

# Uncomment if using PostgreSQL
# volumes:
#   postgres_data: 